apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: multicloud-lab
resources:
- kubernetes/namespace.yaml
- kubernetes/deployment.yaml
- kubernetes/service.yaml
- kubernetes/rbac.yaml
- kubernetes/observability.yaml
configMapGenerator:
- name: lab-app
  literals:
  - APP_ENV=kubernetes
  - ENABLE_FAULTS=false
  - LOG_DIR=/var/log/lab
- name: alloy-config
  files:
  - config.alloy=observability/alloy/config.alloy
- name: prometheus-config
  files:
  - prometheus.yml=observability/prometheus/kubernetes.yml
  - alerts.yml=observability/prometheus/alerts.yml
- name: loki-config
  files:
  - config.yml=observability/loki/config.yml
- name: alertmanager-config
  files:
  - alertmanager.yml=observability/alertmanager/alertmanager.yml
- name: grafana-datasources
  files:
  - datasources.yml=observability/grafana/provisioning/datasources/datasources.yml
- name: grafana-provider
  files:
  - dashboards.yml=observability/grafana/provisioning/dashboards/dashboards.yml
- name: grafana-dashboard
  files:
  - lab.json=observability/grafana/dashboards/lab.json
