{
 "title": "Multi-cloud DevOps Observability Lab",
 "tags": [
  "cloud-engineering",
  "observability"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Traffic - requests/sec",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(lab_http_requests_total{job=\"lab-api\"}[2m]))"
    }
   ]
  },
  {
   "title": "Errors - 5xx ratio",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(lab_http_requests_total{job=\"lab-api\",status=~\"5..\"}[2m])) or vector(0)) / clamp_min(sum(rate(lab_http_requests_total{job=\"lab-api\"}[2m])), 0.001)"
    }
   ]
  },
  {
   "title": "Latency - p95",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(lab_http_request_duration_seconds_bucket{job=\"lab-api\"}[2m])))"
    }
   ]
  },
  {
   "title": "Saturation proxy - active requests",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(lab_http_requests_in_progress{job=\"lab-api\"})"
    }
   ]
  },
  {
   "title": "API process memory",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"lab-api\"})"
    }
   ]
  },
  {
   "title": "API process CPU cores",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"lab-api\"}[2m]))"
    }
   ]
  },
  {
   "title": "Structured application logs",
   "type": "logs",
   "gridPos": { "x": 0, "y": 24, "w": 24, "h": 10 },
   "targets": [
    {
     "expr": "{job=\"lab-api\"} | json"
    }
   ]
  }
 ]
}