apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-api
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: lab-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: lab-api
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
      - name: api
        image: multicloud-lab-api:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - configMapRef:
            name: lab-app
        securityContext: &id001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: logs
          mountPath: /var/log/lab
        - name: tmp
          mountPath: /tmp
      - name: alloy
        image: grafana/alloy:v1.10.2
        args:
        - run
        - --storage.path=/var/lib/alloy
        - /etc/alloy/config.alloy
        securityContext: *id001
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: logs
          mountPath: /var/log/lab
          readOnly: true
        - name: alloy-config
          mountPath: /etc/alloy
        - name: alloy-data
          mountPath: /var/lib/alloy
      volumes:
      - name: logs
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      - name: alloy-data
        emptyDir: {}
      - name: alloy-config
        configMap:
          name: alloy-config
