apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lab-api
  namespace: multicloud-lab
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lab-api
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu
      container: api
      target:
        type: Utilization
        averageUtilization: 70
